[template]
src = "haproxy.cfg"
dest = "/etc/haproxy/haproxy.cfg"
mode = "0644"
owner = "haproxy"
keys = [
  "/services/http",
]
check_cmd = "/usr/sbin/haproxy -q -c -f {{.src}}"
reload_cmd = "kill -s HUP `pgrep haproxy`"